name: torch2.0
channels:
  - pytorch
  - huggingface
  - nvidia
  - defaults
dependencies:
  - blas=1.0=mkl
  - brotli-python=1.0.9=py39hd77b12b_8
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - pip:
      - accelerate==0.34.2
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - albucore==0.0.23
      - albumentations==2.0.5
      - aliyun-python-sdk-core==2.15.2
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.4.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asgiref==3.8.1
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==24.2.0
      - babel==2.16.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cffi==1.17.1
      - chroma-hnswlib==0.7.6
      - chromadb==1.0.7
      - click==8.1.8
      - coloredlogs==15.0.1
      - comm==0.2.2
      - corr-sampler==0.0.0
      - crcmod==1.7
      - cryptography==43.0.1
      - datasets==3.0.0
      - debugpy==1.8.5
      - decorator==5.1.1
      - deform-conv==0.0.0
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - diffusers==0.30.3
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - durationpy==0.9
      - einops==0.8.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fastapi==0.115.9
      - fastjsonschema==2.20.0
      - ffmpy==0.5.0
      - filelock==3.16.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gast==0.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-auth==2.39.0
      - googleapis-common-protos==1.70.0
      - gradio==4.44.1
      - gradio-client==1.3.0
      - greenlet==3.1.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.4
      - httpx==0.27.2
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.10
      - importlib-metadata==8.5.0
      - inquirerpy==0.3.4
      - intel-openmp==2021.4.0
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.1
      - jmespath==0.10.0
      - json5==0.9.25
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.2
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kubernetes==32.0.1
      - langchain==0.2.3
      - langchain-core==0.2.40
      - langchain-text-splitters==0.2.4
      - langsmith==0.1.121
      - lightning-utilities==0.3.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - mkl==2021.4.0
      - mmh3==5.1.0
      - modelscope==1.11.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.2.2
      - notebook-shim==0.2.4
      - numpy==1.26.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime==1.19.2
      - onnxsim==0.4.36
      - opencv-python-headless==4.11.0.86
      - opentelemetry-api==1.32.1
      - opentelemetry-exporter-otlp-proto-common==1.32.1
      - opentelemetry-exporter-otlp-proto-grpc==1.32.1
      - opentelemetry-instrumentation==0.53b1
      - opentelemetry-instrumentation-asgi==0.53b1
      - opentelemetry-instrumentation-fastapi==0.53b1
      - opentelemetry-proto==1.32.1
      - opentelemetry-sdk==1.32.1
      - opentelemetry-semantic-conventions==0.53b1
      - opentelemetry-util-http==0.53b1
      - orjson==3.10.7
      - oss2==2.19.0
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.2.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pfzy==0.3.4
      - pip==25.1.1
      - platformdirs==4.3.3
      - posthog==4.0.1
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==5.29.4
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pycryptodome==3.20.0
      - pydantic==2.11.3
      - pydantic-core==2.33.1
      - pydeprecate==0.3.2
      - pydub==0.25.1
      - pygments==2.18.0
      - pypdf2==3.0.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==2.0.7
      - python-multipart==0.0.20
      - pytorch-lightning==1.6.5
      - pytz==2024.2
      - pywavelets==1.6.0
      - pywin32==306
      - pywinpty==2.0.13
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests-oauthlib==2.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.20.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - ruff==0.11.7
      - safetensors==0.4.5
      - scipy==1.13.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentence-transformers==4.1.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - setuptools==80.8.0
      - shellingham==1.5.4
      - simplejson==3.19.3
      - simsimd==6.2.1
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.35
      - stack-data==0.6.3
      - starlette==0.45.3
      - stringzilla==3.12.5
      - tbb==2021.13.1
      - tenacity==8.5.0
      - tensorrt==10.9.0.34
      - terminado==0.18.1
      - tf-keras==2.19.0
      - timm==0.6.2.dev0
      - tinycss2==1.3.0
      - tokenizers==0.19.1
      - tomli==2.0.1
      - tomlkit==0.12.0
      - torchaudio==2.3.1
      - torchmetrics==0.11.4
      - torchvision==0.18.1
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers==4.44.2
      - typer==0.15.3
      - types-python-dateutil==2.9.0.20240906
      - typing-extensions==4.12.2
      - typing-inspection==0.4.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.2.3
      - uvicorn==0.34.2
      - wandb==0.19.11
      - watchfiles==1.0.5
      - wcwidth==0.2.13
      - webcolors==24.8.0
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - xxhash==3.5.0
      - yapf==0.40.2
      - yarl==1.11.1
      - zipp==3.20.2
prefix: C:\ProgramData\anaconda3\envs\torch2.0
